server:
  port: 8282
spring:
  datasource:
    username: root
    password: qwer1234
    url: jdbc:mysql://127.0.0.1:3306/vlog?characterEncoding=utf-8&serverTimezone=PRC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 192.168.52.128
    port: 6379
    password: qwer1234
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
#    jackson:
#      default-property-inclusion: non_null # JSON处理时忽略非空字段
  servlet:
    multipart: #上传文件的限制大小
      max-file-size: 100MB
      max-request-size: 1000MB
    #Spring Boot 默认是不注入这些属性值的，需要自己绑定
    #druid 数据源专有配置
      #配置监控统计拦截的filters，stat:监控统计、log4j：日志记录、wall：防御sql注入
      #如果允许时报错  java.lang.ClassNotFoundException: org.apache.log4j.Priority
      #则导入 log4j 依赖即可，Maven 地址：https://mvnrepository.com/artifact/log4j/log4j

  thymeleaf:
    cache: false
    enabled: true
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
mybatis:
  type-aliases-package: edu.zut.vlog.pojo
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
pagehelper:
  helper-dialect: mysql
  reasonable: true
logging:
  level:
    com.hmdp: debug
